# Generated by Django 2.0.4 on 2018-05-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bnetName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='steamName',
            field=models.TextField(null=True),
        ),
    ]
