# Generated by Django 2.0.4 on 2018-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180526_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
