# Generated by Django 2.0.4 on 2018-05-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('pkMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('fkRemitente', models.IntegerField()),
                ('fkDestinatario', models.IntegerField()),
                ('asunto', models.TextField(max_length=150)),
                ('cuerpo', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
