# Generated by Django 2.0.4 on 2018-05-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fkRemitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje', to='usuarios.User'),
        ),
    ]
