# Generated by Django 2.0.4 on 2018-05-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_auto_20180526_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fkDestinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_dest', to='usuarios.User'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fkRemitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_rem', to='usuarios.User'),
        ),
    ]
